### ISSUE TITLE
如何使用Cookie登录

### ISSUE THREAD

**Issue by Ra2-IFV** [Executor-Cheng/ExtendNetease_DGJModule#5]
好多Cookie啊到底要复制哪个...

**Comment by JSssssss** [comment]
> 好多Cookie啊到底要复制哪个...

这个看源代码能看出来吗？

**Comment by horizon86** [comment]
> > 好多Cookie啊到底要复制哪个...
> 
> 这个看源代码能看出来吗？

@JSssssss f12找个网络请求复制cookie就行
