### ISSUE TITLE
无法播放会员歌曲，可能是因为API地址变化（附新API地址）

### ISSUE THREAD

**Issue by Kamilet** [Executor-Cheng/ExtendNetease_DGJModule#7]
黑胶会员登陆后无效，无法播放会员歌曲。根据 @某只毛玉 老师检查，可能是API地址更换的问题。
由于我不知道怎么编译，烦请作者查是不是API接口的问题。

请尝试将地址：
https://music.163.com/weapi/v1/user/detail/{userId}

换成：
https://music.163.com/api/v1/user/detail/{userId}

试试看，感谢您的付出！

**Comment by NightFullMoon** [comment]
Very good plug-in, love from Bilibili
——————————————————
非常好的插入，爱来自B站

**Comment by Executor-Cheng** [comment]
已在#8 中完成修复
